import * as mc from "@minecraft/server";
import * as mcui from "@minecraft/server-ui"


// ******************* forms instances
const icon_lookup = {
	"travel":		undefined,
	"floatfly":		undefined,
	"snowliquid":	undefined,
	"riding":		undefined,
	"mechanoids":		undefined,
	"vehiclick":		'textures/twf/calm/items/vehiclick.png',
	"bugs":		undefined,
	"moths":		'textures/twf/calm/items/moth.png',
	"dragonfly":		'textures/twf/calm/items/dragonfly.png',
	"items":		undefined,
	"lifecells":	undefined,
	"tools":	undefined,
	"thelittlebook": 'textures/twf/calm/items/twf_calm_guide.png',
	"controller": undefined,
	"destroyer": undefined,
	"buidler": undefined,
	"randomizer": undefined,
	"converter": undefined,
	"lifeswords": undefined,
	"soulballs": undefined,
	"axeofaxolotls": 'textures/twf/calm/items/twf_calm_axe_of_axolotl_item_tex.png',
	"equipment": undefined,
	"goggles": 'textures/twf/calm/items/goggles.png',
	"flightstick": undefined,
	"wings": 'textures/twf/calm/items/wings.png',
	"carapaceandwings": 'textures/twf/calm/items/carapice_wings.png',
	"armor": undefined,
	"carapace": 'textures/twf/calm/items/carapice.png',
	"mobs": undefined,
	"animals": undefined,
	"gliders": 'textures/twf/calm/icons/glider.png',
	"gameplay": undefined,
	"gameoflife": undefined,
	"glider": undefined,
	"repeater": undefined,
	"building": undefined,
	"mobfarm": undefined,
	"stacking": undefined,
	"settings_inst":'textures/blocks/command_block',
	"settings":		'textures/blocks/command_block',
	"performance_inst":'textures/items/tipped_arrow_swift',
	"performance":		'textures/items/tipped_arrow_swift',
	"life_rules_inst":'textures/items/brewing_stand',
	"life_rules":		'textures/items/brewing_stand',
	"crafting": undefined,
	"attributes": undefined,
	"use": undefined,
	
	"about": 		'textures/items/ruby',
	"craft": 		'textures/blocks/crafting_table_top',
	"howto": 		undefined,
	"help": 		'textures/items/totem',
	"calm_tools":	'textures/twf/calm/items/twf_calm_control_tex.png',
	"life":			'textures/twf/calm/icons/critter_icon.png',
	"critter":		'textures/twf/calm/items/critter.png',
	"control": 		'textures/twf/calm/items/twf_calm_control_tex.png',
	"cell":			'textures/twf/calm/blocks/cell/cell_icon.png',
	"build":		'textures/twf/calm/items/twf_calm_build_tex.png',
	"convert": 		'textures/twf/calm/items/twf_calm_converter_tex.png',
	"destroy": 		'textures/twf/calm/items/twf_calm_destroy_tex.png',
	"flight": 		'textures/twf/calm/items/twf_calm_flight_item_tex.png',
	"random": 		'textures/twf/calm/items/twf_calm_random_tex.png',
	"poster": 		'textures/twf/calm/items/twf_calm_poster_tex.png',
	"swords": 		'textures/twf/calm/items/twf_calm_sword_of_life_item_tex.png',
	"lifecage":		'textures/items/snowball',
	"mechanoid": 	'textures/twf/calm/items/twf_calm_mechanoid_tex.png',
	"credits" :		'textures/items/experience_bottle',
	"compat":		'textures/items/book_writable',
	"twf":			'textures/twf/calm/icons/twf.png',
	"changes":		'textures/items/clock_item',
	"contents":		'textures/blocks/bookshelf',
	"settings_inst":'textures/blocks/command_block',
	"settings":		'textures/blocks/command_block',
	"performance_inst":'textures/items/tipped_arrow_swift',
	"performance":		'textures/items/tipped_arrow_swift',
	"life_rules_inst":'textures/items/brewing_stand',
	"life_rules":		'textures/items/brewing_stand'	
};


const info_forms_simple_contents = [   // Convenience approach for simple forms. Forms config is autogenerated at startup
	//  Page Alias (used in navigation, language config keys, and so on
	["contents", ["travel", "items", "mobs", "gameplay", "help", "about"]],
	["about", ["twf","compat","credits","changes","contents"]],
	["craft", ["thelittlebook","poster", "cell", "control", "build", "random", "destroy","vehiclick","mechanoid","carapaceandwings","swords","contents"]],
	["howto", ["flight", "cell", "control", "random", "destroy","contents"]],
	["calm_tools", ["control", "cell", "build", "convert", "destroy", "flight", "random", "poster", "swords", "lifecage","contents"]],
	["control", ["tools","items", "cell","craft","contents"]],
	["cell", ["destroy","items","life_rules_inst","craft","contents"]],
	["build", ["tools","items", "cell","craft","contents"]],
	["convert", ["tools","items","cell","craft","contents"]],
	["destroy", ["tools","items","convert","craft","contents"]],
	["flight", ["tools","items","settings_inst","craft","contents"]],
	["random", ["tools","items","craft","contents"]],
	["poster", ["tools","items","craft","contents"]],
	["swords", ["lifecage","mechanoid","tools","items","settings_inst","craft","contents"]],
	["lifecage", ["items","calm_tools","contents"]],
	["life", ["critter","mechanoid","contents"]],
	["mechanoid", ["mobs","craft","contents"]],
	["critter", ["cell","carapace","goggles","mobs","riding","contents"]],
	["settings_inst", ["contents","settings"]],
	["performance_inst", ["contents","performance"]],
	["life_rules_inst", ["contents","life_rules"]],
	["credits", ["about","contents"]],
	["twf", ["about","prj1","prj2","prj3","prj4","prj5","prj6","prj7","prj8","prj9","prj10","prj11","prj12","prj13","contents"]],
	["prj1", ["twf","contents"]],
	["prj2", ["twf","contents"]],
	["prj3", ["twf","contents"]],
	["prj4", ["twf","contents"]],
	["prj5", ["twf","contents"]],
	["prj6", ["twf","contents"]],
	["prj7", ["twf","contents"]],
	["prj8", ["twf","contents"]],
	["prj9", ["twf","contents"]],
	["prj10", ["twf","contents"]],
	["prj11", ["twf","contents"]],
	["prj12", ["twf","contents"]],
	["prj13", ["twf","contents"]],
	["compat", ["performance_inst","about","contents"]],
	["changes", ["about","contents"]],
	["travel", ["floatfly", "riding","contents"]],
	["floatfly", ["flight", "wings", "carapaceandwings","travel","settings_inst","equipment","contents"]],
	["wings", ["moths", "dragonfly", "carapaceandwings", "travel", "equipment", "contents"]],
	["carapaceandwings", ["carapace", "wings", "travel", "equipment", "craft","contents"]],
	["carapace", ["wings", "carapaceandwings", "equipment", "contents"]],
	["riding", ["critter", "moths", "dragonfly","mechanoid","vehiclick", "travel","contents"]],
	["vehiclick", ["riding","craft","contents"]],
	["moths", ["cell","wings","mobs","riding","contents"]],
	["gliders", ["mobs","contents"]],
	["dragonfly", ["cell","wings","mobs","riding","contents"]],
	["items", ["cell", "tools", "equipment", "contents"]],
	["tools", ["thelittlebook", "control", "destroy", "build", "random", "poster", "convert", "swords", "lifecage", "axeofaxolotls", "items","contents"]],
	["thelittlebook", ["tools","craft","contents"]],
	["axeofaxolotls", ["tools","items","contents"]],
	["equipment", ["goggles", "flight", "wings", "carapace", "carapaceandwings", "items","contents"]],
	["goggles", ["swords","lifecage","equipment","contents"]],
	["mobs", ["critter", "moths", "dragonfly", "gliders", "mechanoid", "contents"]],
	["gameplay", ["howto", "building", "craft","contents"]],
	["building", ["cell","poster","convert","performance_inst","life_rules_inst","gameplay","contents"]],
	["help", ["contents"]],
	["index", [	
				"about",
				"twf",				
				"compat",
				"axeofaxolotls",
				"building",
				"critter",
				"carapace",
				"carapaceandwings",
				"convert",
				"changes",
				"life_rules_inst",
				"settings_inst",
				"contents",
				"craft",
				"mobs",
				"credits",
				"dragonfly",
				"equipment",
				"flight",
				"floatfly",
				"gameplay",
				"gliders",
				"goggles",
				"help",
				"items",
				"build",
				"cell",
				"control",
				"destroy",
				"random",
				"swords",
				"thelittlebook",				
				"mechanoid",
				"moths",
				"travel",
				"calm_tools",
				"poster",
				"performance_inst",
				"riding",
				"lifecage",				
				"tools",
				"howto",
				"vehiclick",
				"wings",

				"prj8",
				"prj6",
				"prj10",
				"prj5",
				"prj3",
				"prj2",
				"prj13",
				"prj11",
				"prj1",
				"prj12",
				"prj4",
				"prj9",
				"prj7"

		]
	]
]

function init_forms(forms_control_guide, ns) {
//  This is modular. Move it into the library for initialisation
	// info_forms_simple_contents.reverse();  // for maintaining list order
	for(let i in info_forms_simple_contents) {
		let buttn = info_forms_simple_contents[i];
		
		let name = buttn[0];
		let icon = icon_lookup[name];

		forms_control_guide[name] = {
			type : 'buttons',
			cache : true,
			title : ns+"guide_form_"+name+"_title" ,
			body : ns+"guide_form_"+name+"_body" ,
			nav : []
		}
		
		if(info_forms_simple_contents[i].length > 1) {
			for(let j in info_forms_simple_contents[i][1]) {
				let subform = info_forms_simple_contents[i][1][j];
				// mc.world.sendMessage(subform)				
				forms_control_guide[name]["nav"].push([ns+"guide_button_"+subform, icon_lookup[subform], subform]);
			}
		};
		
		//  Link back to Contents
		// let row = [ns+"guide_button_"+name, icon, name];
		// forms_control_guide["contents"]["nav"].unshift(row);
	}
	// info_forms_simple_contents.reverse();	// undo
	
	forms_control_guide["contents"]["nav"].push([ns+"guide_button_settings" , icon_lookup["settings_inst"], "settings_inst"]);
	forms_control_guide["contents"]["nav"].push([ns+"guide_button_performance" , icon_lookup["performance_inst"], "performance_inst"]);
	forms_control_guide["contents"]["nav"].push([ns+"guide_button_life_rules" , icon_lookup["life_rules_inst"], "life_rules_inst"]);
	forms_control_guide["contents"]["nav"].push([ns+"guide_button_index" , icon_lookup["index"], "index"]);
	// forms_control_guide["contents"]["nav"].push([ns+"index" , undefined, undefined]);
	forms_control_guide["contents"]["nav"].push([ns+"guide_exit" , undefined, undefined]);
	
	forms_control_guide["settings_inst"]["type"] = "yesno";  // I want this to warn/instruct
	forms_control_guide["performance_inst"]["type"] = "yesno";  // I want this to warn/instruct
	forms_control_guide["life_rules_inst"]["type"] = "yesno";  // I want this to warn/instruct
	
};

export { init_forms };