const bonus_items = [
	"twf_calm:axe_of_axolotl",
	"twf_calm:guide",
	"twf_calm:sword_of_allay",
	"twf_calm:sword_of_armor_stand",
	"twf_calm:sword_of_arrow",
	"twf_calm:sword_of_axolotl",
	"twf_calm:sword_of_bat",
	"twf_calm:sword_of_bee",
	"twf_calm:sword_of_blaze",
	"twf_calm:sword_of_boat",
	"twf_calm:sword_of_camel",
	"twf_calm:sword_of_cat",
	"twf_calm:sword_of_cave_spider",
	"twf_calm:sword_of_chest_boat",
	"twf_calm:sword_of_chest_minecart",
	"twf_calm:sword_of_chicken",
	"twf_calm:sword_of_cod",
	"twf_calm:sword_of_cow",
	"twf_calm:sword_of_creeper",
	"twf_calm:sword_of_dolphin",
	"twf_calm:sword_of_donkey",
	"twf_calm:sword_of_dragon_fireball",
	"twf_calm:sword_of_drowned",
	"twf_calm:sword_of_egg",
	"twf_calm:sword_of_elder_guardian",
	"twf_calm:sword_of_enderman",
	"twf_calm:sword_of_endermite",
	"twf_calm:sword_of_ender_crystal",
	"twf_calm:sword_of_ender_dragon",
	"twf_calm:sword_of_ender_pearl",
	"twf_calm:sword_of_evocation_illager",
	"twf_calm:sword_of_eye_of_ender_signal",
	"twf_calm:sword_of_fireball",
//	"twf_calm:sword_of_fireworks_rocket",
	"twf_calm:sword_of_fox",
	"twf_calm:sword_of_frog",
	"twf_calm:sword_of_ghast",
	"twf_calm:sword_of_glow_squid",
	"twf_calm:sword_of_goat",
	"twf_calm:sword_of_guardian",
	"twf_calm:sword_of_hoglin",
	"twf_calm:sword_of_hopper_minecart",
	"twf_calm:sword_of_horse",
	"twf_calm:sword_of_husk",
	"twf_calm:sword_of_iron_golem",
	"twf_calm:sword_of_life",
	"twf_calm:sword_of_lightning_bolt",
//	"twf_calm:sword_of_lingering_potion",
	"twf_calm:sword_of_llama",
//	"twf_calm:sword_of_llama_spit",
	"twf_calm:sword_of_magma_cube",
	"twf_calm:sword_of_minecart",
	"twf_calm:sword_of_mooshroom",
	"twf_calm:sword_of_mule",
	"twf_calm:sword_of_ocelot",
	"twf_calm:sword_of_panda",
	"twf_calm:sword_of_parrot",
	"twf_calm:sword_of_phantom",
	"twf_calm:sword_of_piglin_brute",
	"twf_calm:sword_of_piglin",
	"twf_calm:sword_of_pig",
	"twf_calm:sword_of_pillager",
	"twf_calm:sword_of_polar_bear",
	"twf_calm:sword_of_pufferfish",
	"twf_calm:sword_of_rabbit",
	"twf_calm:sword_of_ravager",
	"twf_calm:sword_of_salmon",
	"twf_calm:sword_of_sheep",
//	"twf_calm:sword_of_shulker_bullet",
	"twf_calm:sword_of_shulker",
	"twf_calm:sword_of_silverfish",
	"twf_calm:sword_of_skeleton_horse",
	"twf_calm:sword_of_skeleton",
	"twf_calm:sword_of_slime",
//	"twf_calm:sword_of_small_fireball",
	"twf_calm:sword_of_sniffer",
//	"twf_calm:sword_of_snowball",
	"twf_calm:sword_of_snow_golem",
	"twf_calm:sword_of_spider",
//	"twf_calm:sword_of_splash_potion",
	"twf_calm:sword_of_squid",
	"twf_calm:sword_of_stray",
	"twf_calm:sword_of_strider",
	"twf_calm:sword_of_tadpole",
//	"twf_calm:sword_of_thrown_trident",
	"twf_calm:sword_of_tnt",
	"twf_calm:sword_of_tnt_minecart",
	"twf_calm:sword_of_trader_llama",
	"twf_calm:sword_of_tropicalfish",
	"twf_calm:sword_of_turtle",
	"twf_calm:sword_of_vex",
	"twf_calm:sword_of_villager",
	"twf_calm:sword_of_villager_v2",
	"twf_calm:sword_of_vindicator",
	"twf_calm:sword_of_wandering_trader",
	"twf_calm:sword_of_warden",
	"twf_calm:sword_of_witch",
	"twf_calm:sword_of_wither",
	"twf_calm:sword_of_wither_skeleton",
//	"twf_calm:sword_of_wither_skull_dangerous",
//	"twf_calm:sword_of_wither_skull",
	"twf_calm:sword_of_wolf",
//	"twf_calm:sword_of_xp_bottle",
//	"twf_calm:sword_of_xp_orb",
	"twf_calm:sword_of_zoglin",
	"twf_calm:sword_of_zombie_horse",
	"twf_calm:sword_of_zombie",
	"twf_calm:sword_of_zombie_pigman",
	"twf_calm:sword_of_zombie_villager",
	"twf_calm:sword_of_zombie_villager_v2"
]

export { bonus_items as default, bonus_items };